### ISSUE TITLE
Start to create a settings activity / page

### ISSUE THREAD

**Issue by JonoTheWhite** [kyleb000/Plan-It-To-Do-App#13]
Hi Kyle,
Can you start working on the settings page
Add things you would like for example -
- Custom Ring / notification tone.
- turn notifications on / off.
- link to facebook / twitter etc.

Start creating a rough activity with the simple UI elements, I will edit the UI later.
from there I can create accurate database models for us to get the up developed.
faster and easier.

Thank you.

**Comment by kyleb000** [comment]
sure. But I'll only be able to work on it after my exams

**Comment by kyleb000** [comment]
Could we rather work on that on a later version of the app? For now, I just want the basic functionality done, then we can start adding stuff like that.
