### ISSUE TITLE
Landscape mode crashes

### ISSUE THREAD

**Issue by JonoTheWhite** [kyleb000/Plan-It-To-Do-App#21]
need to fix landscape orientation from crashing (add / fix landscape layouts)

**Comment by kyleb000** [comment]
App still crashes when in horizontal mode. Here is the error: 

FATAL EXCEPTION: main
Process: za.co.brdsa.kyle.planitto_doapp, PID: 17547
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
at za.co.brdsa.kyle.planitto_doapp.views.ToDoListAdapter.getView(ToDoListAdapter.java:61)

**Comment by JonoTheWhite** [comment]
It is working, you will just have to pull the new changes GIT.
The Null Pointer is due created because the layout file (xml) is not in your project.
PS I will be changing layouts soon. just very busy with work at the moment.

**Comment by kyleb000** [comment]
You need to push first.
