### ISSUE TITLE
List View and Text View cutting of bits of sentence

### ISSUE THREAD

**Issue by kyleb000** [kyleb000/Plan-It-To-Do-App#4]
It appears that the List View and the text view is cutting out bits of the sentence at the end.
![screenshot_2016-05-18-09-26-15](https://cloud.githubusercontent.com/assets/11809643/15350704/0d76782e-1cdb-11e6-9f40-9fd9720a280e.png)

**Comment by JonoTheWhite** [comment]
Fixed ;-)

**Comment by kyleb000** [comment]
Task definition is no longer cutting, but name still is.

**Comment by JonoTheWhite** [comment]
fixed

**Comment by kyleb000** [comment]
only reopening this issue because no changes were pushed to the repository
